CREATE TABLE AUTHORS(
  INT(11) NOT NULL AUTO_INCREMENT,
  AUTHOR_NAME VARCHAR(255) NOT NULL,
  EMAIL VARCHAR(255),
  ALIAS VARCHAR(255),
  PRIMARY KEY(AUTHOR_ID)
);

CREATE TABLE CATEGORIES(
    CAT_ID INT(11) NOT NULL AUTO_INCREMENT,
    CAT_NAME VARCHAR(255),
    DESCRIPTION TEXT,
    PRIMARY KEY(CAT_ID)
);

CREATE TABLE POSTS(
    POST_ID INT(11) NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(255) NOT NULL,
    AUTHOR_ID INT(11) NOT NULL,
    BODY TEXT,
    CREATE_DATE TIMESTAMP,
    PRIMARY KEY(POST_ID),
    CONSTRAINT FK_POST_AUTHORS_AUTHOR_ID FOREIGN KEY(AUTHOR_ID) REFERENCES AUTHORS(AUTHOR_ID)
);

CREATE TABLE POSTS_CATS(
  POST_ID INT(11) NOT NULL,
  CAT_ID INT(11) NOT NULL,
  PRIMARY KEY(POST_ID, CAT_ID),
  CONSTRAINT FK1 FOREIGN KEY(POST_ID) REFERENCES POSTS(POST_ID),
  CONSTRAINT FK2 FOREIGN KEY(CAT_ID) REFERENCES CATEGORIES(CAT_ID),
);